#!/usr/bin/python3

import unittest
import composertest


class TestImages(composertest.ComposerTestCase):
    """
        This is the "entry-point" to the test suite when
        executed in Cockpit CI. If $TEST_SCENARIO=="" or
        $TEST_SCENARIO="images" we end up here.

        New test methods should be added here first!
        When this target becomes too slow we split out into
        separate scenarios!
    """
    def test_blueprint_sanity(self):
        self.runCliTest("/tests/cli/test_blueprints_sanity.sh")

    def test_compose_sanity(self):
        self.runCliTest("/tests/cli/test_compose_sanity.sh")

    def test_ext4_filesystem(self):
        self.runCliTest("/tests/cli/test_compose_ext4-filesystem.sh")

    def test_partitioned_disk(self):
        self.runCliTest("/tests/cli/test_compose_partitioned-disk.sh")


class TestQcow2(composertest.ComposerTestCase):
    def test_qcow2(self):
        self.runCliTest("/tests/cli/test_compose_qcow2.sh")


class TestLiveIso(composertest.ComposerTestCase):
    def test_live_iso(self):
        self.runCliTest("/tests/cli/test_compose_live-iso.sh")

class TestRepos(composertest.ComposerTestCase):
    def test_repos_sanity(self):
        self.runCliTest("/tests/cli/test_repos_sanity.sh")


class TestTar(composertest.ComposerTestCase):
    def test_tar(self):
        self.runCliTest("/tests/cli/test_compose_tar.sh")

    @unittest.skip("No such file: 'new-kernel-pkg' in Fedora 30 anaconda. Enable with Fedora 31")
    def test_tar_kickstart(self):
        self.runCliTest("/tests/cli/test_compose_tar_kickstart.sh")


if __name__ == '__main__':
    composertest.main()
