#!/usr/bin/python3

import composertest


class TestImages(composertest.ComposerTestCase):
    """
        This is the "entry-point" to the test suite when
        executed in Cockpit CI. If $TEST_SCENARIO=="" or
        $TEST_SCENARIO="images" we end up here.

        New test methods should be added here first!
        When this target becomes too slow we split out into
        separate scenarios!
    """
    def test_blueprint_sanity(self):
        self.runCliTest("/tests/cli/test_blueprints_sanity.sh")

    def test_compose_sanity(self):
        self.runCliTest("/tests/cli/test_compose_sanity.sh")


if __name__ == '__main__':
    composertest.main()
