#!/bin/sh -e
# This is the expected entry point for Cockpit CI; will be called without
# arguments but with an appropriate $TEST_OS, and optionally $TEST_SCENARIO

make vm

if [ -n "$TEST_SCENARIO" ]; then
  if [ "$TEST_SCENARIO" == "live-iso" ]; then
    test/check-cli TestLiveIso
  elif [ "$TEST_SCENARIO" == "qcow2" ]; then
    test/check-cli TestQcow2
  elif [ "$TEST_SCENARIO" == "tar" ]; then
    test/check-cli TestTar
  else
    test/check-cloud TestCloud.test_$TEST_SCENARIO
  fi
else
  test/check-cli TestImages
  test/check-api
  test/check-cli TestRepos
fi
