#!/bin/sh -eux

SRPM="$1"

# Grow root partition to make room for images. This only works on Fedora right now.
echo ", +" | sfdisk -N 2 -f /dev/vda
partprobe
pvresize /dev/vda2
lvresize fedora/root -l+100%FREE -r

su builder -c "/usr/bin/mock --no-clean --resultdir build-results --rebuild $SRPM"

packages=$(find build-results -name '*.rpm' -not -name '*.src.rpm')
rpm -e $(basename -a ${packages[@]} | sed 's/-[0-9].*.rpm$//') || true
yum install -y beakerlib $packages

systemctl enable lorax-composer.socket
systemctl enable docker.service
