FROM registry.fedoraproject.org/fedora:30
RUN  dnf -y install \
  anaconda-tui \
  libgit2-glib \
  libselinux-python3 \
  make \
  pykickstart \
  python3-coverage \
  python3-coveralls \
  python3-flask \
  python3-gevent \
  python3-magic \
  python3-mako \
  python3-nose \
  python3-pocketlint \
  python3-pylint \
  python3-pyparted \
  python3-pytoml \
  python3-semantic_version \
  python3-sphinx \
  python3-rpmfluff \
  python3-librepo \
  python3-pyvmomi \
  beakerlib \
  sudo \
  tito \
  rsync \
  e2fsprogs \
  xz-lzma-compat \
  pbzip2 \
  squashfs-tools \
  qemu-img \
  which && \
  touch /.in-container
RUN useradd weldr
VOLUME /lorax-ro
VOLUME /test-results
WORKDIR /lorax-ro
