FROM fedora:29

RUN dnf -y install make libgit2-glib tito python3-pylint  \
                    python3-nose python3-mako python3-flask \
                    python3-coverage libselinux-python3 sudo \
                    pykickstart python3-pytoml python3-sphinx \
                    python3-semantic_version \
                    anaconda-tui

RUN mkdir /lorax
COPY . /lorax

WORKDIR /lorax
RUN make test
