#!/usr/bin/env python

import sys
import toml

if len(sys.argv) != 3:
    print("USAGE: ", __file__, "<blueprint-one.toml> <blueprint-two.toml>")
    sys.exit(1)

blueprint_one = toml.loads(open(sys.argv[1]).read())
blueprint_two = toml.loads(open(sys.argv[2]).read())

assert blueprint_one == blueprint_two
